[tool.poetry]
name = "machine-learning"
version = "0.1.0"
description = "Machine Learning Notebooks for learning and exploring"
authors = ["Malik Naik <maliknaik16@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
torch = "^2.6.0"
torchvision = "^0.21.0"
ipykernel = "^6.29.5"
matplotlib = "^3.10.0"
numpy = "^2.2.3"
pandas = "^2.2.3"
torchsummary = "^1.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
